version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: coffee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/coffee-shop
    image: coffee-shop-backend
    environment:
      SPRING_APPLICATION_NAME: coffee-shop
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coffee_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: "true"
      BOT_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - db
    ports:
      - "8080:8080"

  bot:
    build:
      context: ./backend/coffee-shop-bot
    image: coffee-shop-bot
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - backend
    # ports: если нужен, например:
    # - "5000:5000"

  frontend:
    build:
      context: ./frontend/coffee-shop
    image: coffee-shop-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    environment:
      VITE_API_URL: http://backend:8080
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  pgdata:
